# Generated by Django 5.2.3 on 2025-06-22 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude coordinate')),
                ('longitude', models.FloatField(help_text='Longitude coordinate')),
                ('offset_angle', models.FloatField(blank=True, help_text='Optional offset angle between ground surface and horizontal line', null=True)),
                ('optimal_pitch', models.FloatField(help_text='Optimal tilt angle in degrees')),
                ('optimal_azimuth', models.FloatField(help_text='Optimal azimuth angle in degrees')),
                ('annual_solar_radiation', models.FloatField(help_text='Annual solar radiation in kWh/m²/day')),
                ('efficiency_factor', models.FloatField(help_text='System efficiency factor (0-1)')),
                ('estimated_annual_output', models.FloatField(help_text='Estimated annual energy output in kWh')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('calculation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='solar_solar_latitud_a852e9_idx'), models.Index(fields=['created_at'], name='solar_solar_created_6456d5_idx')],
            },
        ),
    ]
