apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-backend
  labels:
    app: solar-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solar-backend
  template:
    metadata:
      labels:
        app: solar-backend
    spec:
      containers:
      - name: solar-backend
        image: solar-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: solar-secrets
              key: secret-key
        - name: ALLOWED_HOSTS
          value: "solar-backend,solar-frontend"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: solar-backend-service
spec:
  selector:
    app: solar-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP 