apiVersion: v1
kind: ConfigMap
metadata:
  name: solar-config
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "solar-backend,solar-frontend"
  REACT_APP_API_URL: "http://solar-backend-service"
---
apiVersion: v1
kind: Secret
metadata:
  name: solar-secrets
type: Opaque
data:
  secret-key: eW91ci1zZWNyZXQta2V5LWhlcmUtY2hhbmdlLWluLXByb2R1Y3Rpb24=  # base64 encoded 